### PR TITLE
client: add support for api/v1/links, automate parser generation

### PR DESCRIPTION
**Pull request by virtualtam**
Suggested CLI usage:

```bash
$ shaarli [GLOBAL OPTIONS] <HTTP_METHOD>-<ENDPOINT> [ENDPOINT OPTIONS]

# e.g.:
$ shaarli -u URL -s SECRET --output pprint get-info
$ shaarli -u URL -s SECRET get-links --offset 36 --searchtags tag1 tag2 --limit all
```

---

https://shaarli.github.io/api-documentation/#links-links-collection-get

Added:
- api/v1/links endpoint support
- let the client hold endpoint metadata:
  - parser commands
  - API path
  - HTTP method
  - help
  - allowed parameters, when applicable
- parser <-> client utilities:
  - generate endpoint subparsers from client metadata
  - retrieve valid endpoint parameters from parsed data
- raise an Exception if invalid parameters are passed

Changed:
- cli: display the help if no endpoint is selected
- cli: refactor parser and argument definition
- pydocstyle: disable D213 - Multi-line docstring summary should start at the second line
     (conflicts with D212 - Multi-line docstring summary should start at the first line)

See:
- https://docs.python.org/3.5/library/argparse.html
- error handling:
  - https://docs.python.org/3/library/exceptions.html
  - https://stackoverflow.com/questions/1319615/proper-way-to-declare-custom-exceptions-in-modern-python
  - http://doc.pytest.org/en/latest/assert.html
- introspection:
  - https://docs.python.org/3.5/library/functions.html#getattr
  - https://docs.python.org/3.5/library/functions.html#hasattr
  - https://www.python.org/dev/peps/pep-0274/
  - https://stackoverflow.com/questions/14507591/python-dictionary-comprehension#14507637
- collections, tuples & unpacking:
  - https://docs.python.org/3/tutorial/controlflow.html#unpacking-argument-lists
  - https://docs.python.org/3.5/library/collections.html#collections.OrderedDict

---

code-review-is-coming

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
Multiple word tag/term search doesn't work, the `+` is URL encoded:

```
 ➜ shaarli -u http://localhost.localdomain:8080 -s jaimeLePate --output pprint get-links --searchtags php+bus
[]
```

[Sun Feb 19 17:50:07 2017] ::1:59308 [200]: /api/v1/links?searchtags=**php%2Bbus**

**Comment by virtualtam** [comment]
Thanks @ArthurHoaro!

I'm going to rework this PR so each new feature (utilities, parser generation, endpoint metadata) is introduced in a dedicated commit and more thoroughly tested :)

**Comment by virtualtam** [comment]
@nodiscc @ArthurHoaro I'll merge this PR in a couple days so we can issue a first release on PyPI and move on to add new features :)

I've also started working on a way to test the client against an actual Shaarli instance, or write tests using recorded HTTP interactions (using [Betamax](https://betamax.readthedocs.io/en/latest/))

**Comment by ArthurHoaro** [comment]
Well, I still have the exact same issue.

**Comment by virtualtam** [comment]
Hmm...
Did you by any chance reuse the same testing virtual environment?

I suspect the installation docs I wrote are erroneous as the following two commands are not equivalent:

```bash
$ python setup.py install 
# correctly builds and installs the application in the virtualenv
```

```bash
$ pip install . 
# builds and installs the application in the virtualenv, but doesn't seem to handle
# CLI entrypoints, so the `shaarli` script stills points to a previously installed version
```

**Comment by ArthurHoaro** [comment]
> Did you by any chance reuse the same testing virtual environment? 

Yes I did, I didn't really take a look at the code sorry. I'll take a look tomorrow.

**Comment by ArthurHoaro** [comment]
No luck. I don't think I made a mistake.

```bash
➜ git log --format="%H" -n 1 | tee
d72032918da505eba782a277915764a49295a97b
➜ python --version
Python 3.6.0
➜ rm -rf /home/arthur/.virtualenvs/shaarli/
➜ python3 -m venv ~/.virtualenvs/shaarli
# probably useless?
(shaarli) ➜ source ~/.virtualenvs/shaarli/bin/activate
(shaarli) ➜ pip install . 
(shaarli) ➜ python setup.py install
(shaarli) ➜ pip freeze                  
PyJWT==1.4.2
requests==2.13.0
requests-jwt==0.4
shaarli-client==0.1.0
(shaarli) ➜ shaarli -u http://localhost.localdomain:8080 -s jaimeLePate --output pprint get-links --limit 1          
http://localhost.localdomain:8080/api/v1/links?limit=1
[
    {
        "created": "2017-02-10T20:07:41+01:00",
        "description": "<...>",
        "id": 804,
        "private": true,
        "shorturl": "Rvr-iw",
        "tags": [],
        "title": "<...>",
        "updated": "2017-03-08T18:59:50+01:00",
        "url": "<...>"
    }
]
(shaarli) ➜ shaarli -u http://localhost.localdomain:8080 -s jaimeLePate --output pprint get-links --searchtags php+bus
http://localhost.localdomain:8080/api/v1/links?searchtags=php%2Bbus
[]
```

**Comment by virtualtam** [comment]
Ow, that's to be expected then, sorry I forgot to specify how the parser works :p

It expects search{tags, terms} to be passed as a space-separated "list", e.g.:

```bash
$ shaarli -u http://localhost.localdomain:8080 -s jaimeAussiLaChoucroute --output pprint get-links --searchtags php bus
```

The parser provides a list of search strings, that is joined by spaces and URL-encoded by requests. It's worth mentioning that a space is URL-encoded to a `+` (it's part of a set of special HTTP entities); to avoid conflicts, a `+` is URL-encoded to `%2B`

Relevant documentation:
- https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20#1634293
- https://stackoverflow.com/questions/6855624/plus-sign-in-query-string
- https://www.w3.org/Addressing/URL/4_URI_Recommentations.html
- https://tools.ietf.org/html/rfc3986#section-2

**Comment by ArthurHoaro** [comment]
Awesome it works! Note that I used your original post.

**Comment by virtualtam** [comment]
\o/

> Note that I used your original post.

Didn't see this one coming! Post edited, I'll check the commit messages for potential misdirections

**Pull request merged**
