### PR TITLE
allow "python -m shaarli_client.main"

### PR DESCRIPTION
**Pull request by clach04**

### CODE REVIEW

**Comment by nodiscc** [comment]
Hi,
What is the purpose of this change?

**Comment by clach04** [comment]
@nodiscc  when I ran (headrevs):

    python -m shaarli_client.main

Nothing happens, no output.

With the change it's callable, e.g. in this instance help gets shown:

    (py37venv) C:\code\py\python-shaarli-client>python -m shaarli_client.main --help
    usage: main.py [-h] [-c CONFIG] [-i INSTANCE] [-u URL] [-s SECRET]
                   [-f {json,pprint,text}] [-o OUTFILE] [--insecure]
                   {get-info,get-links,post-link,put-link,get-tags,get-tag,put-tag,delete-tag,delete-link}
                   ...

    positional arguments:
      {get-info,get-links,post-link,put-link,get-tags,get-tag,put-tag,delete-tag,delete-link}
                            REST API endpoint
        get-info            Get information about this instance
        get-links           Get a collection of links ordered by creation date
        post-link           Create a new link or note
        put-link            Update an existing link or note
        get-tags            Get all tags
        get-tag             Get a single tag
        put-tag             Rename an existing tag
        delete-tag          Delete a tag from every link where it is used
        delete-link         Delete a link

    optional arguments:
      -h, --help            show this help message and exit
      -c CONFIG, --config CONFIG
                            Configuration file
      -i INSTANCE, --instance INSTANCE
                            Shaarli instance (configuration alias)
      -u URL, --url URL     Shaarli instance URL
      -s SECRET, --secret SECRET
                            API secret
      -f {json,pprint,text}, --format {json,pprint,text}
                            Output formatting
      -o OUTFILE, --outfile OUTFILE
                            File to save the program output to
      --insecure            Bypass API SSL/TLS certificate verification

**Comment by nodiscc** [comment]
@clach04 Thanks!
Can you please rebase your changes on `master`? Tests were failing for unrelated reasons, should be fixed now.

**Comment by clach04** [comment]
@nodiscc  I could (and if it's really necessary I will)... But you should have an option via this page to rebase and merge with a few clicks.

image

is what I would expected your view to look like, you'd need to pick the bottom one (rather than the top one).

Let me know 🤞

**Comment by nodiscc** [comment]
I'm aware of the possibility to squash commits during merge, but I'd like this to be rebased _before_ merging, to allow tests to run on the branch. Thanks

**Comment by clach04** [comment]
@nodiscc I just rebased and pushed, hopefully this should allow the tests to run 🤞. Let me know :-)

**Review by nodiscc — APPROVED** [review]
Thanks

**Pull request merged**
